export const jobTypes = {
    SAVE_CURRENT_JOB: 'SAVE_CURRENT_JOB',
    SAVE_ALL_JOBS: 'SAVE_ALL_JOBS',
    SAVE_APPLIED_JOBS: 'SAVE_APPLIED_JOBS',
    DELETE_CURRENT_JOB: 'DELETE_CURRENT_JOB',
    FILTER_SEARCH_JOBS: 'FILTER_SEARCH_JOBS',
    FILTER_APPLIED_JOBS: 'FILTER_APPLIED_JOBS',
}

export const candidateTypes = {
    SAVE_CURRENT_CANDIDATE: 'SAVE_CURRENT_CANDIDATE',
    SAVE_ALL_CANDIDATES: 'SAVE_ALL_CANDIDATES',
    DELETE_CURRENT_CANDIDATE: 'DELETE_CURRENT_CANDIDATE',
    FILTER_SEARCH_CANDITATE: 'FILTER_SEARCH_CANDITATE',
    CHANGE_STATUS: 'CHANGE_STATUS'
}

export const authTypes = {
    AUTH: 'AUTH',
    SAVE_DATA: 'SAVE_DATA'
}

export const rolesTypes = {
    SAVE_CURRENT_ROLE: 'SAVE_CURRENT_ROLE',
    SAVE_ALL_ROLES: 'SAVE_ALL_ROLES',
    DELETE_CURRENT_ROLE: 'DELETE_CURRENT_ROLE',
    FILTER_SEARCH_ROLES: 'FILTER_SEARCH_ROLES',
}

export const adminTypes = {
    SAVE_CURRENT_ADMIN: 'SAVE_CURRENT_ADMIN',
    SAVE_ALL_ADMINS : 'SAVE_ALL_ADMINS',
    DELETE_CURRENT_ADMIN: 'DELETE_CURRENT_ADMIN',
    FILTER_SEARCH_ADMINS: 'FILTER_SEARCH_ADMIN',
}

export const currentUserTypes = {
    SAVE_USER_DATA: 'SAVE_USER_DATA'
}
