export const jobTypes = {
    SAVE_CURRENT_JOB: 'SAVE_CURRENT_JOB',
    SAVE_ALL_JOBS: 'SAVE_ALL_JOBS',
    SAVE_APPLIED_JOBS: 'SAVE_APPLIED_JOBS',
    DELETE_CURRENT_JOB: 'DELETE_CURRENT_JOB',
    FILTER_SEARCH_JOBS: 'FILTER_SEARCH_JOBS',
    FILTER_APPLIED_JOBS: 'FILTER_APPLIED_JOBS',
}

export const candidateTypes = {
    SAVE_CURRENT_CANDIDATE: 'SAVE_CURRENT_CANDIDATE',
    SAVE_ALL_CANDIDATES: 'SAVE_ALL_CANDIDATES',
    DELETE_CURRENT_CANDIDATE: 'DELETE_CURRENT_CANDIDATE',
    FILTER_SEARCH_CANDITATE: 'FILTER_SEARCH_CANDITATE',
    CHANGE_STATUS: 'CHANGE_STATUS'
}

export const authTypes = {
 LOG_IN: 'LOG_IN',
 LOG_OUT: 'LOG_OUT'
}
